blank_issues_enabled: false
contact_links:
  - name: 4ac Matrix
    url: https://matrix.to/#/#neuboard:matrix.org
    about: General chat about Neuboard and quick Q/A
  - name: 4a9 Questions / Feedback
    url: https://github.com/neuboard/neuboard/discussions/new/choose
    about: Post your questions or feedback in the discussions panel
