name: 4a5 Crash report
description: Create a report with a generated crash log attached to help Neuboard improve
labels:
  - "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your help in making Neuboard better!
        Guide to a good crash-report:
        539 Please search existing bug/crash reports to avoid creating duplicates.
        539 Give your crash report a good name (no generics like "Error" or "Crash"), so others can easily identify the topic of your issue.
        539 Describe what you were doing what could've led to the crash and whether the crash is random or reproducible.
  - type: textarea
    id: description
    attributes:
      label: Short description
      description: Describe the bug in a short but concise way.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See crash
    validations:
      required: true
  - type: textarea
    id: crashlog
    attributes:
      label: Crash log
      description: Paste the generated crash log below
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I made sure that there are *no existing issues* - [open](https://github.com/neuboard/neuboard/issues) or [closed](https://github.com/neuboard/neuboard/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to."
          required: true
        - label: "I have read and understood the [contribution guidelines](https://github.com/neuboard/neuboard/blob/main/CONTRIBUTING.md)."
          required: true
        - label: "I have taken the time to fill in all the required details. I understand that the crash report will be dismissed otherwise."
          required: true
